-- OpenAPI compatibility platform schema. Append-only events; no row is ever deleted.
create table if not exists spec (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  role varchar(16) not null,
  fingerprint char(64) not null unique,
  media_type varchar(64) not null,
  content clob not null,
  created_at_ms bigint not null
);

create table if not exists sample_batch (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  snapshot_fingerprint char(64) not null unique,
  sample_count int not null,
  created_at_ms bigint not null
);

create table if not exists sample (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references sample_batch(id),
  sample_key varchar(255) not null,
  content_fingerprint char(64) not null,
  payload clob not null,
  unique (batch_id, sample_key),
  unique (batch_id, content_fingerprint)
);

-- A run ("排练") is fully determined by baseline fingerprint + candidate fingerprint
-- + sample-set snapshot fingerprint + policy version. The unique key is the cache:
-- two parallel candidate versions can never share a cached report.
create table if not exists run (
  id bigint generated by default as identity primary key,
  run_fingerprint char(64) not null unique,
  baseline_id bigint not null references spec(id),
  candidate_id bigint not null references spec(id),
  sample_batch_id bigint not null references sample_batch(id),
  policy_version varchar(32) not null,
  baseline_fingerprint char(64) not null,
  candidate_fingerprint char(64) not null,
  snapshot_fingerprint char(64) not null,
  report clob not null,
  created_at_ms bigint not null
);

-- Append-only audit ledger for every human decision. Revocation/undo inserts a new row.
create table if not exists event (
  id bigint generated by default as identity primary key,
  event_type varchar(48) not null,
  exemption_id bigint,
  decision_id bigint,
  run_id bigint,
  finding_id varchar(16),
  method varchar(16),
  path varchar(512),
  change_code varchar(64),
  reason varchar(4096),
  actor varchar(255),
  before_version char(64),
  after_version char(64),
  valid_from_ms bigint,
  valid_to_ms bigint,
  disposition varchar(32),
  created_at_ms bigint not null
);

create table if not exists exemption (
  id bigint generated by default as identity primary key,
  exemption_key char(64) not null unique,
  run_id bigint not null,
  finding_id varchar(16) not null,
  method varchar(16) not null,
  path varchar(512) not null,
  change_code varchar(64) not null,
  anchor varchar(1024) not null,
  subject varchar(1024),
  bound_candidate_fingerprint char(64) not null,
  baseline_fingerprint char(64) not null,
  valid_from_ms bigint not null,
  valid_to_ms bigint not null,
  status varchar(16) not null,
  reason varchar(4096) not null,
  actor varchar(255) not null,
  granted_event_id bigint,
  revoked_event_id bigint,
  created_at_ms bigint not null,
  updated_at_ms bigint not null
);

create table if not exists decision (
  id bigint generated by default as identity primary key,
  decision_key char(64) not null unique,
  run_id bigint not null,
  finding_id varchar(16) not null,
  disposition varchar(32) not null,
  reason varchar(4096) not null,
  actor varchar(255) not null,
  active boolean not null,
  created_at_ms bigint not null,
  updated_at_ms bigint not null
);
